# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Xingjian Xuanyuan
tagline:          'Personal Website'
description:      'Tao is to the world what rivers are to the ocean.'
baseurl:          https://XingjianXuanyuan.github.io/

include: ["_pages", "_posts"]

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

author:
  name:           'Xingjian Xuanyuan'
  url:            https://github.com/XingjianXuanyuan

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/XingjianXuanyuan/XingjianXuanyuan.github.io