# Build settings
markdown:             kramdown
kramdown:
  input:              GFM
  syntax_highlighter_opts:
    default_lang:     C
    css_class:        'syntax'
highlighter:          rouge
excerpt_separator:    <!-- excerpt-end -->
mathjax:              true

# Permalinks
permalink:        pretty

# Setup
title:            Xingjian Xuanyuan
tagline:          'Personal Website'
description:      '譬大道之在天下猶川谷之於江海'
baseurl:          https://XingjianXuanyuan.github.io/

include: ["_pages", "_posts"]

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

author:
  name:           'Xingjian Xuanyuan'
  url:            https://github.com/XingjianXuanyuan

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/XingjianXuanyuan/XingjianXuanyuan.github.io